# == Schema Information
# Schema version: 20081111194114
#
# Table name: users
#
#  id               :integer(4)      not null, primary key
#  login            :string(255)
#  crypted_password :string(255)
#  password_salt    :string(255)
#  remember_token   :string(255)
#  login_count      :integer(4)
#  last_request_at  :datetime
#  last_login_at    :datetime
#  current_login_at :datetime
#  last_login_ip    :string(255)
#  current_login_ip :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class User < ActiveRecord::Base  
  # ---------------------------------------
  # The following code has been generated by role_requirement.
  # You may wish to modify it to suit your need
  has_and_belongs_to_many :roles
  
  # has_role? simply needs to return true or false whether a user has a role or not.  
  # It may be a good idea to have "admin" roles return true always
  def has_role?(role_in_question)
    @_list ||= self.roles.collect(&:name)
    return true if @_list.include?("admin")
    (@_list.include?(role_in_question.to_s) )
  end
  # ---------------------------------------
  
  acts_as_authentic
  
end
